name       : hnterm
version    : 0.4
release    : 1
source     :
    - git|https://github.com/ggerganov/hnterm.git : v0.4
homepage   : https://hnterm.ggerganov.com/
license    : MIT
component  : network.news
summary    : Hacker News in the terminal
description: |
    Browse Hacker News interactively in your terminal.
builddeps  :
    - pkgconfig(libcurl)
    - git
setup      : |
    %cmake
build      : |
    %make
install    : |
    install -Dm00755 bin/hnterm $installdir/usr/bin/hnterm
